// Actions
export const ACTION_SET_DATA = "ACTION_SET_DATA";
export const ACTION_SET_LANGUAGE = "SET_LANGUAGE";
export const ACTION_SET_DATE_PRECISION = "ACTION_SET_DATE_PRECISION";

// Date accuracy
export const DATE_PRECISION_DAY = "DATE_PRECISION_DAY";
export const DATE_PRECISION_MONTH = "DATE_PRECISION_MONTH";
export const DATE_PRECISION_YEAR = "DATE_PRECISION_YEAR";
