// Actions
export const ACTION_SET_DATA = "ACTION_SET_DATA";
export const ACTION_SET_LANGUAGE = "SET_LANGUAGE";
export const ACTION_SET_DATE_ACCURACY = "ACTION_SET_DATE_ACCURACY";

// Date accuracy
export const DATE_ACCURACY_DAY = "DATE_ACCURACY_DAY";
export const DATE_ACCURACY_MONTH = "DATE_ACCURACY_MONTH";
export const DATE_ACCURACY_YEAR = "DATE_ACCURACY_YEAR";
